name: RCA test site
favicon: null
layout_spectrum: 0.9225959624163806
typography_spectrum: 0.7780321869067848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.20665500755421817
  lightness: 0.3283801896031946
  saturation: 0.3469339271541685
  rhythmicContrast: 0.4306692536920309
purpose: []
